name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@"${{ secrets.EC2_IP }}" << 'EOF'
            # Move to home directory
            cd ~
            ll
            # Clone the repo if it doesn't exist
            # if [ ! -d "notes-backend" ]; then
            #   git clone https://github.com/YOUR_USERNAME/notes-backend.git
            # fi

            cd notes-backend

            # Pull latest changes
            git pull origin main

            # Install Node.js if not installed
            # if ! command -v node &> /dev/null; then
            #   curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            #   sudo apt-get install -y nodejs
            # fi

            # Install PM2 globally if not available
            # if ! command -v pm2 &> /dev/null; then
            #   sudo npm install -g pm2
            # fi

            # Install dependencies
            npm install

            # Restart or start the app with PM2
            pm2 restart notes-backend || pm2 start server.js --name notes-backend
          EOF
