name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@"${{ secrets.EC2_IP }}" << 'EOF'
            # Go to home directory
            cd ~
            
            # List contents to confirm location
            ls -la

            # Navigate to the project directory
            cd notes-backend

            # Pull latest changes
            git pull origin main

            # Install dependencies
            npm install

            # Restart or start the app with PM2
            pm2 restart notes-backend || pm2 start server.js --name notes-backend
          EOF
